[package]
name = "drum"
version = "0.1.0"
authors = ["Jaye Marshall <marshall.jaye@gmail.com>"]
description = "A bitcask inspired storage api for rust."
license = "MIT"

[dependencies]
bincode = "*"
rustc-serialize = "*"